version: '3.8'
services:
  alltalk-tts:
    image: erew123/alltalk_tts:cuda
    restart: unless-stopped
    ports:
      - "7851:7851"
    volumes:
      - ./outputs:/app/outputs/
      - ./models:/app/models/
      - ./voices:/app/voices/
      - ./finetune/put-voice-samples-in-here:/app/finetune/put-voice-samples-in-here
      - ./dockerconfig.json:/app/confignew.json
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
