name: Simple Workflow Test

on: [push]

jobs:
  runner-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Say Hello
        run: echo "Hello GitHub Actions!"
